---
- name: Install tomcat
  hosts: target_nodes
  gather_facts: no
  vars_files:
    - vars/main.yml
  
  tasks:
    - name: Check if Java is already installed (check version if installed already - java-1.8.0-openjdk.x86_64)

    - name: Install Java (if not already installed)

    - name: Check Java version (ensure Java is properly installed)

    - name: Check if tomcat is already installed (/usr/local/apache-tomcat-8.0.32/)

    - name: Deploy tomcat (if not aleady installed)

    - name: Add startup script (systemd unit file)

    - name: Start tomcat

    - name: Check tomcat is running
  